version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./portfolio/
        target: /home/local/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: >
      sh -c "yarn dev"
